version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: kestra-cloud    # Project ID
    schema: nytaxi            # Dataset name
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
